<?php

declare(strict_types=1);

namespace App\Telegram\Entities;

use Spatie\LaravelData\Dto;
use Spatie\LaravelData\Optional;

final class Message extends Dto
{
    public function __construct(
        public int $message_id,
        public Optional|int $message_thread_id,
        public Optional|User $from,
        public Optional|User $sender_chat,
        public Optional|int $sender_boost_count,
        public Optional|User $sender_business_bot,
        public int $date,
        public Optional|string $business_connection_id,
        public Chat $chat,
        public Optional|MessageOrigin $forward_origin,
        public Optional|bool $is_topic_message,
        public Optional|bool $is_automatic_forward,
        public Optional|self $reply_to_message,
        public Optional|ExternalReplyInfo $external_reply,
        public Optional|TextQuote $quote,
        public Optional|Story $reply_to_story,
        public Optional|User $via_bot,
        public Optional|int $edit_date,
        public Optional|bool $has_protected_content,
        public Optional|bool $is_from_offline,
        public Optional|string $media_group_id,
        public Optional|string $author_signature,
        public Optional|string $text,
        public Optional|array $entities,
        public Optional|LinkPreviewOptions $link_preview_options,
        public Optional|string $effect_id,
        public Optional|Animation $animation,
        public Optional|Audio $audio,
        public Optional|Document $document,
        public Optional|array $paid_media,
        public Optional|array $photo,
        public Optional|Sticker $sticker,
        public Optional|Story $story,
        public Optional|Video $video,
        public Optional|VideoNote $video_note,
        public Optional|Voice $voice,
        public Optional|string $caption,
        public Optional|array $caption_entities,
        public Optional|bool $show_caption_above_media,
        public Optional|bool $has_media_spoiler,
        public Optional|Contact $contact,
        public Optional|Dice $dice,
        public Optional|Game $game,
        public Optional|Poll $poll,
        public Optional|Venue $venue,
        public Optional|Location $location,
        public Optional|array $new_chat_members,
        public Optional|User $left_chat_member,
        public Optional|string $new_chat_title,
        public Optional|array $new_chat_photo,
        public Optional|bool $delete_chat_photo,
        public Optional|bool $group_chat_created,
        public Optional|bool $supergroup_chat_created,
        public Optional|bool $channel_chat_created,
        public Optional|MessageAutoDeleteTimerChanged $message_auto_delete_timer_changed,
        public Optional|int $migrate_to_chat_id,
        public Optional|int $migrate_from_chat_id,
        public Optional|MaybeInaccessibleMessage $pinned_message,
        public Optional|Invoice $invoice,
        public Optional|SuccessfulPayment $successful_payment,
        public Optional|RefundedPayment $refunded_payment,
        public Optional|UsersShared $users_shared,
        public Optional|ChatShared $chat_shared,
        public Optional|string $connected_website,
        public Optional|WriteAccessAllowed $write_access_allowed,
        public Optional|PassportData $passport_data,
        public Optional|ProximityAlertTriggered $proximity_alert_triggered,
        public Optional|ChatBoostAdded $chat_boost_added,
        public Optional|ChatBackground $chat_background_set,
        public Optional|ForumTopicCreated $forum_topic_created,
        public Optional|ForumTopicEdited $forum_topic_edited,
        public Optional|ForumTopicClosed $forum_topic_closed,
        public Optional|ForumTopicReopened $forum_topic_reopened,
        public Optional|GeneralForumTopicHidden $general_forum_topic_hidden,
        public Optional|GeneralForumTopicUnhidden $general_forum_topic_unhidden,
        public Optional|GiveawayCreated $giveaway_created,
        public Optional|Giveaway $giveaway,
        public Optional|GiveawayWinners $giveaway_winners,
        public Optional|GiveawayCompleted $giveaway_completed,
        public Optional|VideoChatScheduled $video_chat_scheduled,
        public Optional|VideoChatStarted $video_chat_started,
        public Optional|VideoChatEnded $video_chat_ended,
        public Optional|VideoChatParticipantsInvited $video_chat_participants_invited,
        public Optional|WebAppData $web_app_data,
        public Optional|InlineKeyboardMarkup $reply_markup,
    ) {}
}
